apiVersion: v1
entries:
  kiali-operator:
  - apiVersion: v2
    appVersion: v1.22.0-SNAPSHOT
    created: "2020-07-27T10:05:27.871848756-04:00"
    description: Kiali is an open source project for service mesh observability, refer
      to https://www.kiali.io for details.
    digest: b616877d1c2a60f50fc81e42f540ae15be33a139d8d136b99dcf5d77f3b3d690
    home: https://github.com/kiali/kiali-operator
    icon: https://raw.githubusercontent.com/kiali/kiali.io/master/themes/kiali/static/img/kiali_logo_masthead.png
    keywords:
    - istio
    - operator
    - kiali
    maintainers:
    - email: kiali-users@googlegroups.com
      name: Kiali
      url: https://kiali.io
    name: kiali-operator
    sources:
    - https://github.com/kiali/kiali-operator/tree/master/charts/kiali-operator
    urls:
    - https://kiali.org/kiali-operator/charts/kiali-operator-v1.22.0-SNAPSHOT.tgz
    version: v1.22.0-SNAPSHOT
generated: "2020-07-27T10:05:27.870999248-04:00"
