dist: xenial
os: linux

arch:
  - amd64
  - arm64
  - ppc64le

jobs:
  # It takes a very long time to spin up an ARM machine on travis.
  # Because of this, we will allow arm64 builds to fail.
  fast_finish: true
  allow_failures:
  - arch: arm64
  - arch: ppc64le
  include:
    - arch: amd64
    - arch: arm64
    - arch: ppc64le

# The channel name "chat.freenode.net#kiali" is encrypted to prevent IRC spam from forks
notifications:
￼ irc:
￼   channels:
      - secure: D7BiCSh0qJzKsEYmWsCdt2XaQve2yQPqF97LaCVU70nNDUMmzwvd8B24lVp4LcmS0t6jkIMvOiLB4PJldjNk/s5Y6IH23+7id/gRFopKLAI2DynqhLlDs0asRRzeUbzDlqdMP8AtyzIUcKnB0MLExoM1TIoHHHc9z1CbyFFFw3JDS12NWf35Lr5KNf0YojtdU/YSDGse33lGuUlZD8p9JacSI09BEUrzgtfuetD5LInbp9f+283hAlj7kY5psonDVvISQTRavT98GIpimo/7Gq0fesKoWPSOks5Y30MkAB+NVfVmECe6r1iqIeUXrdttjTnT+kqiW0OPQPYek5vO9RCr1N7qjhz8xjEbfV5MM5a1utc0VfniLs+1nwHoMqoYW9G8ke2XGgxvWhJyLi8uX6ATutpMMIbVkHsUIx12Y86rxF30VLnt7EhFMZVagp3zcJaoTUua2aXOhpNue3HA2SBpmUW7uqXQyDMf3H27sosdW0isF/J2utYTK+ENv6lyZ7eqDbNnlJiVRGunMfuQosVe+NT5Fpn7k3d+yw94decCMWfxg7SbWapeRcy3V1GTfDo5lhp4qO040Zf9FKa3GCjTXWQFxsFVipllun8aRELibA7uZJnoXEavJNYoaT5TfSFBgBQVfyRkM2X004B+VuALowE2NOYzOqTLgWHPzS8=
￼   on_success: change
￼   on_failure: change

script:
  # ensures we can build the operator on each supported architecture
  # This also downloads operator-sdk which we will use below to validate the metadata.
  - make build

  # test the validity of the ossm metadata
  - _output/operator-sdk-install/operator-sdk version
  - cat manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml | KIALI_OPERATOR_VERSION="2.0.0" KIALI_OLD_OPERATOR_VERSION="1.0.0" KIALI_OPERATOR_TAG=":2.0.0" KIALI_1_12_TAG=":1.12.0" KIALI_1_0_TAG=":1.0.0" CREATED_AT="2020-01-01T00:00:00Z" envsubst > manifests/kiali-ossm/manifests/csv.yaml ; mv manifests/kiali-ossm/manifests/csv.yaml manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  - _output/operator-sdk-install/operator-sdk bundle validate --verbose manifests/kiali-ossm

  # test the validity of the community metadata
  - _output/operator-sdk-install/operator-sdk bundle validate --verbose manifests/kiali-community
  - _output/operator-sdk-install/operator-sdk bundle validate --verbose manifests/kiali-upstream
