{{ if .Values.istio.ingress.enabled }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "kiali-operator.fullname" . }}-virtualservice
  namespace: {{ .Values.cr.spec.deployment.namespace }}
  labels:
  {{- include "kiali-operator.labels" . | nindent 4 }}
spec:
  gateways:
  - {{ include "kiali-operator.fullname" . }}-gateway
  hosts:
  {{- toYaml .Values.istio.ingress.hosts | nindent 4 }}
  http:
  - route:
    - destination:
        host: kiali.{{ .Values.cr.spec.deployment.namespace }}.svc.cluster.local
        port:
          number: 20001
      weight: 100
...
{{- end }}
