---
apiVersion: oauth.openshift.io/v1
kind: OAuthClient
metadata:
  name: {{ kiali_vars_remove.deployment.instance_name + '-' + kiali_vars_remove.deployment.namespace }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: "{{ kiali_vars_remove.deployment.namespace }}"
  name: {{ kiali_vars_remove.deployment.instance_name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "{{ kiali_vars_remove.deployment.namespace }}"
  name: {{ kiali_vars_remove.deployment.instance_name }}-cabundle-openshift
