apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ kiali_vars.deployment.resource_names_prefix }}
  namespace: {{ kiali_vars.deployment.namespace }}
  labels:
    app: kiali
    version: {{ kiali_vars.deployment.version_label }}
    app.kubernetes.io/name: kiali
    app.kubernetes.io/version: {{ kiali_vars.deployment.version_label }}
    app.kubernetes.io/part-of: kiali
data:
  config.yaml: |
    {{ kiali_vars | to_nice_yaml(indent=0) | trim | indent(4) }}
