apiVersion: v1
kind: Service
metadata:
  name: {{ kiali_vars.deployment.instance_name }}
  namespace: "{{ kiali_vars.deployment.namespace }}"
  labels: {{ kiali_resource_metadata_labels }}
  annotations:
{% if kiali_vars.server.web_fqdn|length != 0 and kiali_vars.server.web_schema|length != 0 %}
    kiali.io/external-url: {{ kiali_vars.server.web_schema + '://' + kiali_vars.server.web_fqdn + ((':' + kiali_vars.server.web_port | string) if (kiali_vars.server.web_port | string | length != 0) else '') + (kiali_vars.server.web_root | default('')) }}
{% endif %}
{% if kiali_vars.deployment.service_annotations|length > 0 %}
    {{ kiali_vars.deployment.service_annotations | to_nice_yaml(indent=0) | trim | indent(4) }}
{% endif %}
spec:
{% if kiali_vars.deployment.service_type is defined %}
  type: {{ kiali_vars.deployment.service_type }}
{% endif %}
  ports:
  - name: {{ 'http' if kiali_vars.identity.cert_file == "" else 'tcp' }}
    protocol: TCP
{% if k8s_version is defined and k8s_version is version('1.20', '>=') %}
    appProtocol: {{ 'http' if kiali_vars.identity.cert_file == "" else 'https' }}
{% endif %}
    port: {{ kiali_vars.server.port }}
{% if kiali_vars.deployment.service_type is defined and kiali_vars.deployment.service_type == "NodePort" and kiali_vars.server.node_port is defined %}
    nodePort: {{ kiali_vars.server.node_port }}
{% endif %}
{% if kiali_vars.server.observability.metrics.enabled|bool == True %}
  - name: {{ 'http' if kiali_vars.identity.cert_file == "" else 'tcp' }}-metrics
    protocol: TCP
{% if k8s_version is defined and k8s_version is version('1.20', '>=') %}
    appProtocol: {{ 'http' if kiali_vars.identity.cert_file == "" else 'https' }}
{% endif %}
    port: {{ kiali_vars.server.observability.metrics.port }}
{% endif %}
  selector:
{% if query(k8s_plugin, kind='Service', resource_name=kiali_vars.deployment.instance_name, namespace=kiali_vars.deployment.namespace) | length > 0 %}
    app: null
    version: null
{% endif %}
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: {{ kiali_vars.deployment.instance_name }}
  {% if kiali_vars.deployment.additional_service_yaml is defined %}{{ kiali_vars.deployment.additional_service_yaml | to_nice_yaml(indent=0) | trim | indent(2) }}{% endif %}
