apiVersion: v1
kind: Service
metadata:
  name: {{ kiali_vars.deployment.resource_names_prefix }}
  namespace: {{ kiali_vars.deployment.namespace }}
  labels: {{ kiali_resource_metadata_labels }}
  annotations:
{% if kiali_vars.server.web_fqdn|length != 0 and kiali_vars.server.web_schema|length != 0 %}
    kiali.io/external-url: {{ kiali_vars.server.web_schema + '://' + kiali_vars.server.web_fqdn + ((':' + kiali_vars.server.web_port | string) if (kiali_vars.server.web_port | string | length != 0) else '') + (kiali_vars.server.web_root | default('')) }}
{% endif %}
{% if kiali_vars.deployment.service_annotations|length > 0 %}
    {{ kiali_vars.deployment.service_annotations | to_nice_yaml(indent=0) | trim | indent(4) }}
{% endif %}
spec:
{% if kiali_vars.deployment.service_type is defined %}
  type: {{ kiali_vars.deployment.service_type }}
{% endif %}
  ports:
  - name: {{ 'http' if kiali_vars.identity.cert_file == "" else 'tcp' }}
    protocol: TCP
    port: {{ kiali_vars.server.port }}
{% if kiali_vars.server.metrics_enabled|bool == True %}
  - name: http-metrics
    protocol: TCP
    port: {{ kiali_vars.server.metrics_port }}
{% endif %}
  selector:
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: {{ kiali_vars.deployment.resource_names_prefix }}
  {% if kiali_vars.deployment.additional_service_yaml is defined %}{{ kiali_vars.deployment.additional_service_yaml | to_nice_yaml(indent=0) | trim | indent(2) }}{% endif %}
