apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: kiali-operator.v${KIALI_OPERATOR_VERSION}
  namespace: placeholder
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.s390x: supported
    operatorframework.io/arch.ppc64le: supported
  annotations:
    operators.openshift.io/valid-subscription: '["OpenShift Container Platform", "OpenShift Platform Plus"]'
    olm.skipRange: '>=1.0.0 <${KIALI_OPERATOR_VERSION}'
    categories: Monitoring,Logging & Tracing
    certified: "false"
    containerImage: ${KIALI_OPERATOR_REGISTRY}
    capabilities: Deep Insights
    support: Red Hat
    description: "Kiali project provides answers to the questions: What microservices are part of my Istio service mesh and how are they connected?"
    repository: https://github.com/kiali/kiali
    createdAt: ${CREATED_AT}
    operators.openshift.io/infrastructure-features: '["disconnected"]'
    alm-examples: |-
      [
        {
          "apiVersion": "kiali.io/v1alpha1",
          "kind": "Kiali",
          "metadata": {
            "name": "kiali"
          },
          "spec": {
            "installation_tag": "My Kiali",
            "istio_namespace": "istio-system",
            "deployment": {
              "logger": {
                "log_level": "debug"
              },
              "namespace": "istio-system",
              "view_only_mode": false
            }
          }
        },
        {
          "apiVersion": "monitoring.kiali.io/v1alpha1",
          "kind": "MonitoringDashboard",
          "metadata": {
            "name": "myappdashboard"
          },
          "spec": {
            "title": "My App Dashboard",
            "items": [
              {
                "chart": {
                  "name": "My App Processing Duration",
                  "unit": "seconds",
                  "spans": 6,
                  "metricName": "my_app_duration_seconds",
                  "dataType": "histogram",
                  "aggregations": [
                    {
                      "label": "id",
                      "displayName": "ID"
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
spec:
  version: ${KIALI_OPERATOR_VERSION}
  maturity: stable
  replaces: kiali-operator.v${KIALI_OLD_OPERATOR_VERSION}
  displayName: Kiali Operator
  description: |-
    ## About the managed application

    A Microservice Architecture breaks up the monolith into many smaller pieces
    that are composed together. Patterns to secure the communication between
    services like fault tolerance (via timeout, retry, circuit breaking, etc.)
    have come up as well as distributed tracing to be able to see where calls
    are going.

    A service mesh can now provide these services on a platform level and frees
    the application writers from those tasks. Routing decisions are done at the
    mesh level.

    Kiali works with OpenShift Service Mesh to visualize the service
    mesh topology, to provide visibility into features like circuit breakers,
    request rates and more. It offers insights about the mesh components at
    different levels, from abstract Applications to Services and Workloads.

    See [https://www.kiali.io](https://www.kiali.io) to read more.

    ### Accessing the UI

    By default, the Kiali operator exposes the Kiali UI as an OpenShift Route.

    The default root context path is '/' though you can change
    this by configuring the 'web_root' setting in the Kiali CR.

    ## About this Operator

    ### Kiali Custom Resource Configuration Settings

    For quick descriptions of all the settings you can configure in the Kiali
    Custom Resource (CR), see
    [the kiali.io docs](https://kiali.io/docs/configuration/kialis.kiali.io/).

    ## Prerequisites for enabling this Operator

    Kiali is a companion tool for OpenShift Service Mesh. So before you install Kiali, you must have
    already installed Service Mesh.
  icon:
  - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDIyLjAuMSwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIHZpZXdCb3g9IjAgMCAxMjgwIDEyODAiIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgMCAwIDEyODAgMTI4MDsiIHhtbDpzcGFjZT0icHJlc2VydmUiPgo8c3R5bGUgdHlwZT0idGV4dC9jc3MiPgoJLnN0MHtmaWxsOiMwMTMxNDQ7fQoJLnN0MXtmaWxsOiMwMDkzREQ7fQo8L3N0eWxlPgo8Zz4KCTxwYXRoIGNsYXNzPSJzdDAiIGQ9Ik04MTAuOSwxODAuOWMtMjUzLjYsMC00NTkuMSwyMDUuNS00NTkuMSw0NTkuMXMyMDUuNSw0NTkuMSw0NTkuMSw0NTkuMVMxMjcwLDg5My42LDEyNzAsNjQwCgkJUzEwNjQuNSwxODAuOSw4MTAuOSwxODAuOXogTTgxMC45LDEwMjkuMmMtMjE1LDAtMzg5LjItMTc0LjMtMzg5LjItMzg5LjJjMC0yMTUsMTc0LjMtMzg5LjIsMzg5LjItMzg5LjJTMTIwMC4xLDQyNSwxMjAwLjEsNjQwCgkJUzEwMjUuOSwxMDI5LjIsODEwLjksMTAyOS4yeiIvPgoJPHBhdGggY2xhc3M9InN0MSIgZD0iTTY1My4zLDI4NGMtMTM2LjQsNjAuNS0yMzEuNiwxOTcuMS0yMzEuNiwzNTZjMCwxNTguOCw5NS4yLDI5NS41LDIzMS42LDM1NmM5OC40LTg3LjEsMTYwLjQtMjE0LjMsMTYwLjQtMzU2CgkJQzgxMy43LDQ5OC4zLDc1MS42LDM3MS4xLDY1My4zLDI4NHoiLz4KCTxwYXRoIGNsYXNzPSJzdDEiIGQ9Ik0zNTEuOCw2NDBjMC0xMDkuOCwzOC42LTIxMC41LDEwMi44LTI4OS41Yy0zOS42LTE4LjItODMuNi0yOC4zLTEzMC0yOC4zQzE1MC45LDMyMi4yLDEwLDQ2NC41LDEwLDY0MAoJCXMxNDAuOSwzMTcuOCwzMTQuNiwzMTcuOGM0Ni4zLDAsOTAuNC0xMC4xLDEzMC0yOC4zQzM5MC4zLDg1MC41LDM1MS44LDc0OS44LDM1MS44LDY0MHoiLz4KPC9nPgo8L3N2Zz4K
    mediatype: image/svg+xml
  keywords: ['service-mesh', 'observability', 'monitoring', 'maistra', 'istio']
  maintainers:
  - name: Kiali Developers Google Group
    email: kiali-dev@googlegroups.com
  provider:
    name: Red Hat
  labels:
    name: kiali-operator
  selector:
    matchLabels:
      name: kiali-operator
  links:
  - name: Installation Guide
    url: https://www.kiali.io/docs/installation
  - name: Features
    url: https://www.kiali.io/docs/features
  - name: Documentation Home
    url: https://www.kiali.io
  - name: Blogs and Articles
    url: https://medium.com/kialiproject
  - name: Server and UI Source Code
    url: https://github.com/kiali/kiali
  - name: Operator Source Code
    url: https://github.com/kiali/kiali-operator
  installModes:
  - type: OwnNamespace
    supported: false
  - type: SingleNamespace
    supported: false
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: true
  customresourcedefinitions:
    owned:
    - name: kialis.kiali.io
      group: kiali.io
      description: A configuration file for a Kiali installation.
      displayName: Kiali
      kind: Kiali
      version: v1alpha1
      resources:
      - kind: Deployment
        version: apps/v1
      - kind: Pod
        version: v1
      - kind: Service
        version: v1
      - kind: ConfigMap
        version: v1
      - kind: OAuthClient
        version: oauth.openshift.io/v1
      - kind: Route
        version: route.openshift.io/v1
      - kind: ConsoleLink
        version: consolelinks.console.openshift.io/v1
      specDescriptors:
      - displayName: Kiali Namespace
        description: "The namespace where Kiali and its associated resources will be created. Default: istio-system"
        path: deployment.namespace
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:label'
      - displayName: Verbose Mode
        description: "Determines the priority levels of log messages Kiali will output. Typical values are '3' for INFO and higher priority messages, '4' for DEBUG and higher priority messages (this makes the logs more noisy). Default: 3"
        path: deployment.verbose_mode
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:label'
      - displayName: View Only Mode
        description: "When true, Kiali will be in 'view only' mode, allowing the user to view and retrieve management and monitoring data for the service mesh, but not allow the user to modify the service mesh. Default: false"
        path: deployment.view_only_mode
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:booleanSwitch'
      - displayName: Web Root
        description: "Defines the root context path for the Kiali console, API endpoints and readiness/liveness probes. Default: /"
        path: server.web_root
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:label'
    - name: monitoringdashboards.monitoring.kiali.io
      group: monitoring.kiali.io
      description: A configuration file for defining an individual metric dashboard.
      displayName: Monitoring Dashboard
      kind: MonitoringDashboard
      version: v1alpha1
      resources: []
      specDescriptors:
      - displayName: Title
        description: "The title of the dashboard."
        path: title
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:label'
  apiservicedefinitions: {}
  install:
    strategy: deployment
    spec:
      deployments:
      - name: kiali-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: kiali-operator
          template:
            metadata:
              name: kiali-operator
              labels:
                app: kiali-operator
                # required for the operator SDK metric service selector
                name: kiali-operator
                version: v${KIALI_OPERATOR_VERSION}
                app.kubernetes.io/name: kiali-operator
                app.kubernetes.io/version: v${KIALI_OPERATOR_VERSION}
                app.kubernetes.io/part-of: kiali-operator
              annotations:
                prometheus.io/scrape: "true"
            spec:
              serviceAccountName: kiali-operator
              containers:
              - name: operator
                image: ${KIALI_OPERATOR_REGISTRY}
                imagePullPolicy: "IfNotPresent"
                args:
                - "--zap-log-level=info"
                - "--leader-election-id=kiali-operator"
                securityContext:
                  allowPrivilegeEscalation: false
                  privileged: false
                  runAsNonRoot: true
                  capabilities:
                    drop:
                    - ALL
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: ALLOW_AD_HOC_KIALI_NAMESPACE
                  value: "false"
                - name: ALLOW_AD_HOC_KIALI_IMAGE
                  value: "false"
                - name: PROFILE_TASKS_TASK_OUTPUT_LIMIT
                  value: "100"
                - name: ANSIBLE_DEBUG_LOGS
                  value: "True"
                - name: ANSIBLE_VERBOSITY_KIALI_KIALI_IO
                  value: "1"
                - name: ANSIBLE_CONFIG
                  value: "/etc/ansible/ansible.cfg"
                - name: RELATED_IMAGE_kiali_default
                  value: "${KIALI_1_57}"
                - name: RELATED_IMAGE_kiali_v1_57
                  value: "${KIALI_1_57}"   
                - name: RELATED_IMAGE_kiali_v1_48
                  value: "${KIALI_1_48}"
                - name: RELATED_IMAGE_kiali_v1_36
                  value: "${KIALI_1_36}"
                - name: RELATED_IMAGE_kiali_v1_24
                  value: "${KIALI_1_24}"
                ports:
                - name: http-metrics
                  containerPort: 8080
                resources:
                  requests:
                    cpu: "10m"
                    memory: "64Mi"
              volumes:
              - name: runner
                emptyDir: {}
      clusterPermissions:
      - rules:
        - apiGroups: [""]
          resources:
          - configmaps
          - endpoints
          - pods
          - serviceaccounts
          - services
          - services/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups: [""]
          resources:
          - namespaces
          verbs:
          - get
          - list
          - patch
        - apiGroups: [""]
          resources:
          - secrets
          verbs:
          - create
          - list
          - watch
        - apiGroups: [""]
          resourceNames:
          - cacerts
          - istio-ca-secret
          resources:
          - secrets
          verbs:
          - get
        - apiGroups: [""]
          resourceNames:
          - kiali-signing-key
          resources:
          - secrets
          verbs:
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups: ["apps"]
          resources:
          - deployments
          - replicasets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups: ["autoscaling"]
          resources:
          - horizontalpodautoscalers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups: ["monitoring.coreos.com"]
          resources:
          - servicemonitors
          verbs:
          - create
          - get
        - apiGroups: ["apps"]
          resourceNames:
          - kiali-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups: ["kiali.io"]
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups: ["authorization.k8s.io"]
          resources:
          - selfsubjectaccessreviews
          verbs:
          - list
        - apiGroups: ["rbac.authorization.k8s.io"]
          resources:
          - clusterrolebindings
          - clusterroles
          - rolebindings
          - roles
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups: ["apiextensions.k8s.io"]
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - list
          - watch
        - apiGroups: ["extensions", "networking.k8s.io"]
          resources:
          - ingresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups: ["route.openshift.io"]
          resources:
          - routes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups: ["oauth.openshift.io"]
          resources:
          - oauthclients
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups: ["config.openshift.io"]
          resources:
          - clusteroperators
          verbs:
          - list
          - watch
        - apiGroups: ["config.openshift.io"]
          resourceNames:
          - kube-apiserver
          resources:
          - clusteroperators
          verbs:
          - get
        - apiGroups: ["console.openshift.io"]
          resources:
          - consolelinks
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups: ["monitoring.kiali.io"]
          resources:
          - monitoringdashboards
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        # The permissions below are for Kiali itself; operator needs these so it can escalate when creating Kiali's roles
        - apiGroups: [""]
          resources:
          - configmaps
          - endpoints
          - pods/log
          - pods/proxy
          verbs:
          - get
          - list
          - watch
        - apiGroups: [""]
          resources:
          - namespaces
          - pods
          - replicationcontrollers
          - services
          verbs:
          - get
          - list
          - watch
          - patch
        - apiGroups: [""]
          resources:
          - pods/portforward
          verbs:
          - create
          - post
        - apiGroups: ["extensions", "apps"]
          resources:
          - daemonsets
          - deployments
          - replicasets
          - statefulsets
          verbs:
          - get
          - list
          - watch
          - patch
        - apiGroups: ["batch"]
          resources:
          - cronjobs
          - jobs
          verbs:
          - get
          - list
          - watch
          - patch
        - apiGroups:
          - config.istio.io
          - networking.istio.io
          - authentication.istio.io
          - rbac.istio.io
          - security.istio.io
          - extensions.istio.io
          - telemetry.istio.io
          - gateway.networking.k8s.io
          resources: ["*"]
          verbs:
          - get
          - list
          - watch
          - create
          - delete
          - patch
        - apiGroups: ["apps.openshift.io"]
          resources:
          - deploymentconfigs
          verbs:
          - get
          - list
          - watch
          - patch
        - apiGroups: ["project.openshift.io"]
          resources:
          - projects
          verbs:
          - get
        - apiGroups: ["route.openshift.io"]
          resources:
          - routes
          verbs:
          - get
        - apiGroups: ["monitoring.kiali.io"]
          resources:
          - monitoringdashboards
          verbs:
          - get
          - list
        - apiGroups: ["iter8.tools"]
          resources:
          - experiments
          verbs:
          - get
          - list
          - watch
          - create
          - delete
          - patch
        - apiGroups: ["authentication.k8s.io"]
          resources:
          - tokenreviews
          verbs:
          - create
        serviceAccountName: kiali-operator
