apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
  annotations:
    ansible.sdk.operatorframework.io/verbosity: "1"
  labels:
    kiali.dev: "run-operator-playbook"
spec:

  # Make sure the values below also match those in dev-hosts.yaml

  version: default

  deployment:
    accessible_namespaces:
    - "**"
    custom_dashboards:
      includes:
      - 'go*'
      - 'kiali*'
    image_version: dev
    namespace: istio-system
