apiVersion: oauth.openshift.io/v1
kind: OAuthClient
metadata:
  name: {{ kiali_vars.deployment.instance_name }}-{{ kiali_vars.deployment.namespace }}
  labels: {{ kiali_resource_metadata_labels }}
redirectURIs:
  - {{ kiali_route_url }}
grantMethod: auto
allowAnyScope: true
{% if kiali_vars.auth.openshift.token_inactivity_timeout is defined %}
accessTokenInactivityTimeoutSeconds: {{ kiali_vars.auth.openshift.token_inactivity_timeout }}
{% endif %}
{% if kiali_vars.auth.openshift.token_max_age is defined %}
accessTokenMaxAgeSeconds: {{ kiali_vars.auth.openshift.token_max_age }}
{% endif %}
