apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ kiali_vars.deployment.instance_name }}-service-account
  namespace: "{{ kiali_vars.deployment.namespace }}"
  labels: {{ kiali_resource_metadata_labels }}
