kiali_defaults_remove:
  istio_namespace: ""

  deployment:
    accessible_namespaces: []
    hpa:
      api_version: "autoscaling/v2beta2"
    instance_name: "kiali"

# Will be auto-detected, but for debugging purposes you can force one of these to true
is_k8s: false
is_openshift: false
