template_path: ./apigen-crd.template

source_repositories:
- url: https://github.com/jmazzitelli/kiali-operator
  organization: jmazzitelli
  short_name: kiali-operator
  commit_reference: openapi-crd-generate-api-docs
  crd_paths:
  - crd-docs/crd
  cr_paths:
  - crd-docs/cr
  metadata:
    kialis.kiali.io:
      owner:
      - https://github.com/orgs/kiali/teams/maintainers
