apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  annotations:
    ansible.operator-sdk/verbosity: "1"
spec:
  istio_namespace: ${ISTIO_NAMESPACE}
  version: "${KIALI_CR_SPEC_VERSION}"
  auth:
    strategy: $AUTH_STRATEGY
#    openid:
#      client_id: kiali-app
#      insecure_skip_verify_tls: true
#      issuer_uri: "https://192-168-99-100.nip.io:32000"
#      username_claim: email
#  login_token:
#    signing_key: abc12345

  deployment:
    accessible_namespaces: [ "${ACCESSIBLE_NAMESPACES}" ]
    image_name: $KIALI_IMAGE_NAME
    image_pull_policy: $KIALI_IMAGE_PULL_POLICY
    image_version: $KIALI_IMAGE_VERSION
    namespace: $NAMESPACE
    service_type: $SERVICE_TYPE
    logger:
      log_level: info
