apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ kiali_vars.deployment.resource_names_prefix }}-cabundle
  namespace: {{ kiali_vars.deployment.namespace }}
  labels: {{ kiali_resource_metadata_labels }}
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
