apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali-cabundle
  namespace: {{ kiali_vars.deployment.namespace }}
  labels:
    app: kiali
    version: {{ kiali_vars.deployment.version_label }}
  annotations:
    service.beta.openshift.io/inject-cabundle: true
