{% for namespace in role_namespaces %}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ role_binding_kind }}
metadata:
  name: {{ kiali_vars.deployment.resource_names_prefix }}
  namespace: {{ namespace }}
  labels:
    app: kiali
    version: {{ kiali_vars.deployment.version_label }}
    app.kubernetes.io/name: kiali
    app.kubernetes.io/version: {{ kiali_vars.deployment.version_label }}
    app.kubernetes.io/part-of: kiali
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ role_kind }}
  name: {{ (kiali_vars.deployment.resource_names_prefix + '-viewer') if kiali_vars.deployment.view_only_mode|bool == True else kiali_vars.deployment.resource_names_prefix }}
subjects:
- kind: ServiceAccount
  name: {{ kiali_vars.deployment.resource_names_prefix }}-service-account
  namespace: {{ kiali_vars.deployment.namespace }}
{% endfor %}
