default: {"image_name": "quay.io/kiali/kiali", "image_version": "operator_version"}
v1.24: {"image_name": "quay.io/kiali/kiali", "image_version": "v1.24"}
v1.36: {"image_name": "quay.io/kiali/kiali", "image_version": "v1.36"}
v1.48: {"image_name": "quay.io/kiali/kiali", "image_version": "v1.48"}
v1.57: {"image_name": "quay.io/kiali/kiali", "image_version": "v1.57"}
