default: {"image_name": "quay.io/kiali/kiali", "image_version": "operator_version"}
v1.65: {"image_name": "quay.io/kiali/kiali", "image_version": "v1.65"}
v1.73: {"image_name": "quay.io/kiali/kiali", "image_version": "v1.73"}
v2.4: {"image_name": "quay.io/kiali/kiali", "image_version": "v2.4"}
v2.11: {"image_name": "quay.io/kiali/kiali", "image_version": "v2.11"}