default: {"imageName": "quay.io/kiali/ossmconsole", "imageVersion": "operator_version"}
v1.73: {"imageName": "quay.io/kiali/ossmconsole", "imageVersion": "v1.73"}
v2.4: {"imageName": "quay.io/kiali/ossmconsole", "imageVersion": "v2.4"}
v2.11: {"imageName": "quay.io/kiali/ossmconsole", "imageVersion": "v2.11"}
v2.17: {"imageName": "quay.io/kiali/ossmconsole", "imageVersion": "v2.17"}
