- name: Tests
  hosts: localhost
  connection: local
  vars:
    custom_resource: "{{ lookup('template', cr_file_path) | from_yaml }}"
  tasks:
  - import_tasks: ../common/tasks.yml
  - import_tasks: ../asserts/pod_asserts.yml

  # This test will change some config settings to make sure things work like we expect.
  # We will add additional tasks and asserts in the future to test other config changes.

  # Make sure version label is truncated to the k8s maximum 63 chars and must start/end with alphanum char
  - import_tasks: set-version-label.yml
    vars:
      new_version_label: "1234567890123456789012345678901234567890123456789012345678901234"
  - import_tasks: ../common/wait_for_kiali_cr_changes.yml
  - import_tasks: ../common/wait_for_kiali_running.yml
  - import_tasks: ../common/tasks.yml
  - import_tasks: ../asserts/pod_asserts.yml
  - name: Make sure version_label was truncated properly
    assert:
      that:
      - kiali_configmap.deployment.version_label == "123456789012345678901234567890123456789012345678901234567890XXX"
      - "{{ kiali_deployment.resources[0].metadata.labels.version | length == 63 }}"
