apiVersion: v1
kind: ConfigMap
metadata:
  name: plugin-conf
  namespace: "{{ ossmconsole_vars.deployment.namespace }}"
  labels: {{ ossmconsole_resource_metadata_labels }}
data:
  plugin-config.json: |
    {
    }
